<?php

namespace OldMotorsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MotorsForSaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotorsForSaleRepository extends EntityRepository
{
}
