<?php

namespace OldMotorsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RenovatedMotorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RenovatedMotorsRepository extends EntityRepository
{
}
